### PR TITLE
[WIP] Create and restore wallet page.

### PR DESCRIPTION
**Pull request by metaclips**
This PR implements the create/restore wallet page on fyne
Screenshot 2019-09-09 at 6 01 29 PM
Screenshot 2019-09-09 at 6 01 01 PM
Screenshot 2019-09-09 at 6 01 10 PM

### CODE REVIEW

**Comment by barisere** [comment]
The second screenshot has the decred logo in the background. Should it not be the GoDCR logo instead?

**Comment by metaclips** [comment]
No, theres no godcr logo

**Comment by metaclips** [comment]
I don't think theres a godcr logo.

**Comment by itswisdomagain** [comment]
The work done here should be migrated (copied over) to the fyne package in the master branch. Here are some observations from testing that should be incorporated when porting over to master:

1. Underlined sections should read PIN not Password:
Screenshot 2019-09-11 at 8 42 42 PM

2. This log consistently appears whenever I launch the app, no idea why:
Screenshot 2019-09-11 at 8 47 41 PM

3. Should mention that your PR resolves #420 and more should be done (if/where possible) to achieve a look closer to the mockup images on that issue description.

**Pull request closed without merging**
