### PR TITLE
[WIP] Add function to fetch tickets. Add tickets page on web ui

### PR DESCRIPTION
**Pull request by yaowork**
This creates a function in "walletrpcclient" that fetches all tickets. The web ui utilizes this in displaying the ticket info. 

This is a partial fix for #65 
screencapture-localhost-1234-tickets-2018-12-29-13_19_53

### CODE REVIEW

**Comment by itswisdomagain** [comment]
Hi @codemaestro64, let's pause work on this feature for a moment and focus on tasks with higher priority for now. Will let you know when it's okay to resume work on this feature. Thanks for understanding. The PR will remain open though so it is clear to others that work has already begun on this feature, so no one else duplicates efforts here.

**Comment by raedah** [comment]
Actually we need this. On webui as well as the rest.

**Comment by yaowork** [comment]
was closed due to a forced empty commit. Reopening..

**Comment by itswisdomagain** [comment]
The git history for this PR branch is polluted and no longer in sync with `raedahgroup/master` because of a recent history re-write done on master.

Follow the steps below to re-create this PR
- Keep a copy of this PR branch's code in some folder in your PC for reference
- Delete your forked repo (codemaestro64/godcr)
- Fork https://github.com/raedahgroup/godcr again
- Clone your newly forked repo
- Create a new branch for your work (`git checkout -b tickets`)
- Re-apply the changes you made on this PR to the newly created branch
- Push the new branch and create a new PR
- Delete the copy of this code you saved initially

**Pull request closed without merging**
