### PR TITLE
cli: implement wallet restore from seed

### PR DESCRIPTION
**Pull request by itswisdomagain**
Screenshot 2019-08-21 at 4 07 43 PM

### CODE REVIEW

**Comment by Sirmorrison** [comment]
im not sure if this is normal but after inputting the wallet seed, i had to hit tab key twice before the prompt for a password showed up.

**Review by Sirmorrison — COMMENTED** [review]
PR looks good to go but for the part where i had to hit tab key twice before the prompt to enter passphrase or and invalid seed notification prompt pops up.

**Comment by itswisdomagain** [comment]
That behaviour is as expected @Sirmorrison, compare the screenshot on the PR description.

**Review by Sirmorrison — APPROVED** [review]
Good to go.

**Pull request merged**
